name = "Covenant Weapon Security Protocol";
picture = "logo.paa"; 
logo = "logo.paa";
logoOver = "logo.paa";
tooltip = "CWSP Alpha";
tooltipOwned = "CWSP Owned";
overview = "An immersive security protocol mod for Covenant weaponry. Unauthorized possession has consequences.";
author = "Spector641";
overviewPicture = "preview.png";
